site_name: داکی

copyright: 'Copyright &copy; 2020 Mahdi Majidzadeh'

site_url: 'https://mahdimajidzadeh.github.io/docie/'
site_author: 'Mahdi Majidzadeh'

repo_name: 'docie'
repo_url: 'https://github.com/MahdiMajidzadeh/docie'


docs_dir: 'pages'
site_dir: 'docs'

theme:
  name: 'material'
  custom_dir: theme/

extra_css:
  - 'custom-docs.css'  

nav:
    - Home: index.md